# Generated by Django 5.2.3 on 2025-07-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReceipeName', models.CharField(max_length=100)),
                ('Receipe_Descp', models.TextField()),
                ('Receipe_Image', models.ImageField(upload_to='receipe')),
            ],
        ),
    ]
